import pic_2 from './pic_2.jpg'

let all_product =[
    {
        id:1,
        name:"Happy",
        category:"women",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:2,
        name:"Happy",
        category:"women",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:3,
        name:"Happy",
        category:"women",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:4,
        name:"Happy",
        category:"women",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:5,
        name:"Happy",
        category:"men",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:6,
        name:"Happy",
        category:"men",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:7,
        name:"Happy",
        category:"men",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:8,
        name:"Happy",
        category:"men",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:9,
        name:"Happy",
        category:"kid",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:10,
        name:"Happy",
        category:"kid",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:11,
        name:"Happy",
        category:"kid",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:12,
        name:"Happy",
        category:"kid",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:13,
        name:"Happy",
        category:"women",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
    ,{
        id:14,
        name:"Happy",
        category:"men",
        image:pic_2,
        new_price:50.0,
        old_price:80.5
    }
]

export default all_product